#define SECRET_SSID "ESP32-AlarmSystem"
#define SECRET_PASSWORD "Type a password"
#define SECRET_MQTT_BROKER_ADDRESS "192.168.4.3"
#define SECRET_MQTT_PORT 8883
#define SECRET_MQTT_CLIENT_ID "esp32"
#define SECRET_CA_CERT ("-----BEGIN CERTIFICATE-----\n\
YOUR CA CERTIFICATE\n\
-----END CERTIFICATE-----\n")
#define SECRET_CLIENT_CERT ("-----BEGIN CERTIFICATE-----\n\
YOUR CLIENT CERTIFICATE\n\
-----END CERTIFICATE-----\n")
#define SECRET_CLIENT_KEY ("-----BEGIN PRIVATE KEY-----\n\
YOUR CLIENT KEY\n\
-----END PRIVATE KEY-----\n")